apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
type: Opaque
stringData:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-0.kafka-broker-headless.kafka.svc.cluster.local:9092,kafka-broker-1.kafka-broker-headless.kafka.svc.cluster.local:9092,kafka-broker-2.kafka-broker-headless.kafka.svc.cluster.local:9092"
  KAFKA_CLIENT_ID: "coinbase-websocket-client"
  KAFKA_SECURITY_PROTOCOL: "SaslPlaintext"
  KAFKA_SASL_MECHANISM: "ScramSha256"
  KAFKA_SASL_USERNAME: "user1"
  KAFKA_SASL_PASSWORD: "a93LhjbIFQ"