apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-websocket-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbase-websocket-client
  template:
    metadata:
      labels:
        app: coinbase-websocket-client
    spec:
      containers:
      - name: coinbase-websocket-client
        image: bsamaha/coinbase-websocket-client:latest
        envFrom:
        - secretRef:
            name: coinbase-secrets
        - secretRef:
            name: kafka-user-passwords
        env:
        - name: COINBASE_WEBSOCKET_URL
          value: "wss://advanced-trade-ws.coinbase.com"
        - name: COINBASE_PRODUCT_IDS
          value: "BTC-USD,ETH-USD,DOGE-USD,ZEC-USD,SOL-USD,AAVE-USD,LTC-USD,NEAR-USD,RNDR-USD,AVAX-USD"
        - name: COINBASE_CHANNEL
          value: "candles"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker-headless.default.svc.cluster.local:9092"
        - name: LOG_LEVEL
          value: "Debug"
        - name: KAFKA_SASL_USERNAME
          value: "user1"
        - name: KAFKA_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords
        - name: KAFKA_CLIENT_ID
          value: "coinbase-websocket-client"
        - name: KAFKA_SECURITY_PROTOCOL
          value: "SaslPlaintext"
        - name: KAFKA_SASL_MECHANISM
          value: "ScramSha256"